### ISSUE TITLE
Awesome ban system explications !

### ISSUE THREAD

**Issue by Alevhovic** [kanersps/es_admin#14]
Hello @kanersps,

First, thank you for all the work you've done. 

Next, i have a little issue with the "ban" button and the command.

![image](https://user-images.githubusercontent.com/28044103/64568632-834f2e80-d35b-11e9-8c9d-6948c444d195.png)

# Informations
Artifacts : 1552
EssentialMode : 6.2.2
FiveM client : up to date !

**Comment by kanersps** [comment]
This is a bit odd, it seems that internally not enough arguments were provided. What command did you execute exactly?


________________________________

**Comment by Alevhovic** [comment]
Thanks for the fast answer,

We try to click on the "Ban" button inside the Grey & Red Menu.

**Comment by kanersps** [comment]
Yeah but you said you also tried the command? I’m mostly curious about that one. I haven’t looked at the GUI for quite a while so there may be problems there.


________________________________

**Comment by Alevhovic** [comment]
We try : /ban ID (of the player)

**Comment by kanersps** [comment]
Could you try specifying a time too?

Example: /ban ID 20h


________________________________

**Comment by Alevhovic** [comment]
![image](https://user-images.githubusercontent.com/28044103/64569421-beeaf800-d35d-11e9-8ca5-e9c38bf0a4eb.png)

Thank you man, it is working good ! I didn't know how to do it, maybe you should write it in the .readme ;)

We can use "h" for hours, "d" for days and "y" for year maybe ?

We want to do a "perma" ban...

Thanks again men.

**Comment by kanersps** [comment]
Yes you can use y for years, if I remember correctly you can do -1 for permanent bans


________________________________

**Comment by Alevhovic** [comment]
Thank you @kanersps you are awesome !

Cyril.
