### ISSUE TITLE
When admin menu is opened, not all players are shown (only the ones closeby the admin)

### ISSUE THREAD

**Issue by DataM1nd** [kanersps/es_admin#37]
Hello everyone. I installed es_admin on my FiveM server and it works great. All functions do what they should do. Only one issue: when I am in, let's say Sandy and another player is at the lowest point of the map, he doesn't show up in the admin menu's GUI. It's like when we are to far from each other, players don't show up in the playerslist in the admin panel. Anyone ever experienced this or knows how to solve this? Thanks in advance!

**Comment by RoGueN1HGTmare** [comment]
I experience the same... Any ideas to this problem ?

**Comment by F4nKs204** [comment]
Any solution ?

**Comment by vidorreta1** [comment]
Alguien sabe la solucion? me pasa igual
