### ISSUE TITLE
Es_admin menu home key

### ISSUE THREAD

**Issue by luggz** [kanersps/es_admin#5]
when i open the menu with "HOME" it will open but non responsive..... I can click functions but no result however when I exit the menu I'm then frozen and i see my mouse cursor but cant do any thing at all and no errors..... ingame commands work such as /admin /noclip /bring /go... /spectate does not work. And i can set groups.....

**Comment by ghost** [comment]
im having the same exact issue.

**Comment by Memorphix** [comment]
For it to work, you have to rename the resource to es_admin2

Alternatively if you for some weird reason wouldn't like to rename it, you can do following changes https://github.com/kanersps/es_admin/pull/4/files

**Comment by kanersps** [comment]
Exactly, closing
